### ISSUE TITLE
Create the Materials page

### ISSUE THREAD

**Issue by maksymilian-dabkowski** [Cofan-ALDP/LingView#22]
- design mock-up: https://www.figma.com/file/SVskubppblGl9pbo4kTEbY/LingView-Resources-Page
- All Things A'ingae database: https://airtable.com/invite/l?inviteId=invWHjkaSBXHBvMEk&inviteToken=137f26922422eaf58009150e1f308457cb95b6712c6195ee8ab478fad91a2b05

**Comment by sciepsilon** [comment]
Task size: 2 - 15 hours remaining. There's some complicated machinery here, so Jacob could do it in fewer hours than I could. I know it's close to done, but I don't know exactly what parts remain. Jacob's checklist shows that most things are done, including addressing feedback from the LingView call.

**Comment by sciepsilon** [comment]
Closed (finally!) in #55 

It works with Build & Deploy, but when building the materials page on your own computer, you'll need to supply AIRTABLE_API_KEY and AIRTABLE_BASE_ID as environment variables, or else it won't be able to fetch information from Airtable.

**Comment by sciepsilon** [comment]
One way to do that is, in your local copy of the package.json file, change your preferred rebuild script to include the environment variables using cross-env. For example:
```json
"quick-build": "node preprocessing/rebuild.js && npm run webpack && echo \"Done! index.html is ready. To bundle LingView, run \"npm run bundle\".\""
```
becomes
```json
"quick-build": "cross-env AIRTABLE_BASE_ID=itgoeshere AIRTABLE_API_KEY=itgoeshere node preprocessing/rebuild.js && npm run webpack && echo \"Done! index.html is ready. To bundle LingView, run \"npm run bundle\".\""
```
If you have access to our Airtable (which all ALDP project members do - see the Ultimate Guide), the web can tell you how to find the base ID and api key after you log in.

**Comment by jczimm** [comment]
Congrats! FYI I just took a look at the page on the site, and found that clicking on the link for some materials redirects to the landing page rather than going to the document url. I found that the `a` doesn't have a url specified:

![image](https://user-images.githubusercontent.com/5208059/103958001-ffa57d80-5119-11eb-8341-10963e9a22a8.png)
![image](https://user-images.githubusercontent.com/5208059/103957977-ebfa1700-5119-11eb-991e-9561d9ebb669.png)

**Comment by sciepsilon** [comment]
Thanks, good catch. Some of the URLs we have are currently invalid (anything that links to a directory is going to stay invalid until we make some changes on the library server), so build_materials.js is replacing those invalid URLs with an empty string. This must be the result of that. 

Linking back to the landing page is clearly the wrong behavior here. What's the ideal behavior? I'll try omitting the <a> tag when the URL is empty, and just having a non-link <h3> element in that case.

**Comment by jczimm** [comment]
Aha, that makes sense! Yeah, that seems like a good short-term solution--maybe those `<h3>` elements could each have a `title` property explaining that the material is in the process of being made accessible.

**Comment by sciepsilon** [comment]
Links to directories should now work. Unfortunately, many links still don't work (I think it's an encoding issue). I'll create a separate issue for this.
