### ISSUE TITLE
Create the Resources page

### ISSUE THREAD

**Issue by maksymilian-dabkowski** [Cofan-ALDP/LingView#23]
- skeleton: https://docs.google.com/document/d/1OlzXZNiz-bRPityGlGXQTwlJjmA8ex_aX2FgyGdGU4E/edit?usp=sharing
- link to Archivo Blomberg: Rolf Blomberg Biography: https://www.archivoblomberg.org/rbbiography.htm
- link to FLACSO: https://flacso.edu.ec/lenguas-culturas/?lang=en
- link to content published on Facebook

**Comment by sciepsilon** [comment]
Task size: 1 to 15 hours. Should be easy to translate the Google Doc skeleton into an html page and add that page to the tabs in LingView. The skeleton's not totally complete, so I can fill it out a little bit, and then someone else should edit and perhaps expand it (either by directly editing the html, or by changing the doc and asking me to change the html). We probably need some new css styling to make the html page look good, which should also be pretty easy, although css and aesthetics aren't my strong suit.

**Comment by sciepsilon** [comment]
Done in #48
